import type { NextPage } from "next";
import Head from "next/head";
import CDashboard from "../src/component/homepage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Space Tourism | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CDashboard />
    </>
  );
};

export default Home;
